import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

import Container from "@/components/Container";
import NavBar from "@/components/Nav/NavBar";

import type { PropsWithChildren } from "react";
import { Main } from "next/document";

const notoSans = Noto_Sans();

export const metadata: Metadata = {
  title: "NeckCare - Landing",
  description: "Generated by create next app",
};

type RootLayoutProps = PropsWithChildren;

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" className="scroll-smooth md:scroll-auto">
      <body className={`${notoSans.className} antialiased min-w-96 box-border`}>
        <Container>
          <NavBar />
        </Container>
        <Container>{children}</Container>
      </body>
    </html>
  );
};

export default RootLayout;
